backend: local
base_model: openai-community/gpt2
data:
  column_mapping:
    text: text
  path: ''
  train_split: null
  valid_split: null
hub:
  push_to_hub: true
  token: ${{HF_TOKEN}}
  username: ${{HF_USERNAME}}
log: tensorboard
params:
  batch_size: 2
  block_size: 1024
  epochs: 3
  gradient_accumulation: 4
  lr: 3.0e-05
  mixed_precision: fp16
  model_max_length: 2048
  optimizer: adamw_torch
  peft: true
  scheduler: linear
  target_modules: all-linear
  unsloth: false
project_name: autotrain-ao159-ddjag
task: llm
