task: automatic-speech-recognition
base_model: facebook/wav2vec2-base-960h
project_name: autotrain-asr-hub
log: tensorboard
backend: local

data:
  path: common_voice # this must be the hub dataset name
  train_split: train # this must be the name of the training split in the hub dataset
  valid_split: validation # this must be the name of the validation split in the hub dataset
  column_mapping:
    audio_column: audio # this must be the name of the column containing the audio file paths
    text_column: transcription # this must be the name of the column containing the transcriptions
  using_hub_dataset: true

params:
  max_duration: 30.0
  sampling_rate: 16000
  max_seq_length: 128
  epochs: 3
  batch_size: 8
  lr: 3e-4
  optimizer: adamw_torch
  scheduler: linear
  gradient_accumulation: 1
  mixed_precision: fp16
  weight_decay: 0.01
  warmup_ratio: 0.1
  early_stopping_patience: 3
  early_stopping_threshold: 0.01

hub:
  username: ${HF_USERNAME}
  token: ${HF_TOKEN}
  push_to_hub: true 