task: ASR
base_model: facebook/wav2vec2-base-960h
project_name: autotrain-asr-local
log: tensorboard
backend: local

data:
  path: data/ 
  train_split: train
  valid_split: valid
  column_mapping:
    audio_column: audio 
    text_column: transcription 

params:
  max_duration: 30.0
  sampling_rate: 16000
  max_seq_length: 128
  epochs: 3
  batch_size: 8
  lr: 3e-4
  optimizer: adamw_torch
  scheduler: linear
  gradient_accumulation: 1
  mixed_precision: fp16
  weight_decay: 0.01
  warmup_ratio: 0.1
  early_stopping_patience: 3
  early_stopping_threshold: 0.01

hub:
  username: ${HF_USERNAME}
  token: ${HF_TOKEN}
  push_to_hub: true 